<?php
// $Id: acreat_ubercart.install,v 1.24.2.5 2008/12/14 06:25:21 dww Exp $

/*******************************************************************************
 * HOOKS DRUPAL
 ******************************************************************************/

/**
 * Implementation of hook_install()
 */
function acreat_ubercart_install() {
	// s'assurer que le module uc_store est chargé avant le reste des modules Ubercart
	db_query("UPDATE {system} SET weight = %d WHERE name = '%s'", -1, 'uc_store');
}

/**
 * Implementation of hook_uninstall().
 */
function acreat_ubercart_uninstall() {  }
